CREATE TABLE CDI_PAYS 
(
  CODE_CIO varchar(3) 
, CODE_ISO varchar(3) 
, NOM varchar(50) 
, ANNEE_CREATION int
, ANNEE_DISPARITION int 
) ;

Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('ERI','ER ','ERYTHREE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('ETH','ET ','ETHIOPIE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('ARG','AR ','ARGENTINE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('CRC','CR ','COSTA RICA',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('MOL','MD ','MOLDOVA',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('NZL','NZ ','NOUVELLE ZELANDE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('NOR','NO ','NORVEGE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('BRE','BR ','BRESIL',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('LUX','LU ','LUXEMBOURG',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('CRO','HR ','CROATIE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('HON','HU ','HONGRIE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('ESP','ES ','ESPAGNE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('POR','PT ','PORTUGAL',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('FRA','FR ','FRANCE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('AUS','AU ','AUSTRALIE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('SUI','CH ','SUISSE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('ITA','IT ','ITALIE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('BEL','BE ','BELGIQUE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('RUS','RU ','RUSSIE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('USA','US ','ETATS-UNIS',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('UKR','UA ','UKRAINE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('UZB','UZ ','OUZBEKISTAN',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('KAZ','KZ ','KAZAKHSTAN',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('COL','CO ','COLOMBIE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('POL','PL ','POLOGNE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('VEN','VE ','VENEZUELA',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('GBR','GB ','ROYAUME UNI',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('LIT','LT ','LITUANIE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('JAP','JP ','JAPON',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('CZE','CZ ','REPUBLIQUE TCHEQUE','1993',null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('AUT','AT ','AUTRICHE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('LAT','LV ','LETTONIE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('IRL','IE ','IRLANDE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('AND','AD ','ANDORRE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('SUE','SE ','SUEDE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('SM ','SM ','SAINT-MARIN',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('MC ','MC ','MONACO',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('FIN','FI ','FINLANDE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('EST','EE ','ESTONIE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('MEX','MX ','MEXIQUE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('DEN','DK ','DANEMARK',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('RSA','ZA ','AFRIQUE DU SUD',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('SLV','SI ','SLOVENIE','1991',null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('KEN','KE ','KENYA',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('SLQ','SK ','SLOVAQUIE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('CAN','CA ','CANADA',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('BLR','BY ','BELARUS',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('CHN','CN ','CHINE',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('GER','DE ','ALLEMAGNE','1990',null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('NED','NL ','PAYS-BAS',null,null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('YUG','YU ','YOUGOSLAVIE','1929','2003');
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('TCH','CS ','TCHECOSLOVAQUIE','1918','1992');
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('UAE','AE ','EMIRATS ARABES UNIS','1971',null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('BRN','BH ','BAHREIN','2002',null);
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('URS','SU ','UNION DES REPUBLIQUES SOCIALISTES SOVIETIQUES','1922','1991');
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('GDR','DD ','REPUBLIQUE DEMOCRATIQUE ALLEMANDE','1949','1990');
Insert into CDI_PAYS (CODE_CIO,CODE_ISO,NOM,ANNEE_CREATION,ANNEE_DISPARITION) values ('FRG','DE ','REPUBLIQUE FEDRERALE D''ALLEMAGNE','1949','1990');