UPDATE `CDI_COMMANDE` SET `CO_DATE`= NOW() WHERE 1

UPDATE `CDI_LIVRAISON` SET `DATE_LIV`= NOW() + INTERVAL 2 DAY WHERE 1;

UPDATE `CDI_LIGCDE` SET `DATE_LIV`= (SELECT DATE_LIV FROM CDI_LIVRAISON WHERE LI_NUMERO ='L9701') WHERE 1;

UPDATE `CDI_LIGCDE` SET DATE_LIV = NOW() WHERE CO_NUMERO = 'C9713';

UPDATE `CDI_LIVRAISON` SET DATE_LIV = NOW() WHERE CO_NUMERO = 'C9713';